"""update rooms

Revision ID: 75eed2f71f01
Revises: 74e368ba3bc6
Create Date: 2025-07-02 17:20:14.337208

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "75eed2f71f01"
down_revision: Union[str, None] = "74e368ba3bc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
